linkix/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from post.views import home_view


urlpatterns = [
    path('', home_view, name='home'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('post.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('link-add/', create_link, name='linkadd'),
    path('<str:slug>', ads_view, name="ads_view")
]

account/models.py
from statistics import mode
from xml.dom import UserDataHandler
from django.db import models
from django.contrib.auth.models import User


class UserData(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='user')
    clicklink = models.IntegerField(verbose_name='Linkə keçid(lər)')
    coins = models.IntegerField(verbose_name='Coins')


    def __str__(self):
        return str(self.user)


class Userlinkips(models.Model):
    userdata = models.ForeignKey(UserData, on_delete=models.CASCADE)

    ipaddr = models.CharField(verbose_name='Ip Adres', max_length=15)

    def __str__(self):
        return str(self.userdata)


# Create your models here.

templates/ads.html
{% extends 'base.html' %}


{% load crispy_forms_tags %}
{% block base %}
{% load static %}


<body>

    <div class="all_container">
        <div class="ads_link_block" >

            <progress value="0" max="5" id="progress"></progress>
            
            <div id="ads_link" class="ads_seconds" linkim="{{ link.link }}">
                <span id="ads_seconds_value">5</span> saniyə&nbsp;  sonra&nbsp;  linkə <br>
                yönləndiriləcəksiniz
            </div>
        </div>
     
    
    
          
        <div class="img_container">
            <img src="{% static 'berg2.jpg' %}" alt="" height="100%" class="ads_img">
        </div>
    </div>
    

    



</body>

<script>
    var timeleft = 5;
    var timerigt = 0;
    var link = document.getElementById('ads_link');
    console.log(link)
    var downloadTimer = setInterval(function(){
      if(timeleft < 0 && timerigt > 5){
        clearInterval(downloadTimer);
        window.location.href = link.getAttribute('linkim');
      } else {
      document.getElementById("ads_seconds_value").innerHTML = timeleft;
      document.getElementById("progress").value = timerigt;
      }
      timeleft -= 1;
      timerigt += 1;
    }, 1000);
    
    </script>
{% endblock %}

templates/base.html
<html>
{% load static %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Link yarat</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Laila&family=PT+Sans&family=Poppins:wght@300&display=swap" rel="stylesheet">

</head>
{% block base %}


{% endblock %} 

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</html>

templates/index.html
{% extends 'base.html' %}


{% load crispy_forms_tags %}
{% block base %}
{% load static %}

    <body>
       <div class="container">


        {% if not request.user.is_authenticated %}
        <a href="{% url 'register' %}">
            <div class="index_links">
                Qeydiyyat
            </div>
        </a>
        <a href="{% url 'login' %}">
            <div class="index_links">
                Giriş
            </div>
        </a>
        {% endif %}

            {% if request.user.is_authenticated %}
            <div class="index_links">
                <a href="{% url 'linkadd' %}">Link yarat</a>
            </div>

            <div class="index_links">
                <a href="{% url 'profile' request.user.username %}">Profil səhifəsi</a>
            </div>

            <div class="index_links" style="background-color: red;">
                <a href="{% url 'logout' %}">Çıxış</a>
            </div>
            {% endif %}
       </div>
    </body>

{% endblock %}

templates/link-add.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% block base %}


    <body>
        <div class="container" style="margin-top: 20px;">
            <h3>Link yaratma</h3>
            <form method="post">
            
                {% csrf_token %}
                              
                {% crispy form %}
                
                <input type="submit" value="Link yarat">
       
        </div>
       </body> 
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% block base %}


    <body>
        <div class="container" style="margin-top: 20px;">
            <h3>Giris</h3>
            <form method="post">
            
                {% csrf_token %}
                {{ form|crispy }}
                
               <input type="submit" value="Daxil ol">
            </form>
        </div>
       </body> 
{% endblock %}

templates/profile.html
{% extends 'base.html' %}


{% load crispy_forms_tags %}
{% block base %}
{% load static %}

    <body>
        <div class="profil_general">
            <div class="profil_user">
                <span>{{ user.first_name }}</span>
            </div>
            <div class="profil_slugid">
                ID: {{ user.last_name }}
            </div>
        </div>
        {{ user.username }}

        {% for userdata in user.userdata_set.all %}


        <div class="container-fluid" style="background-color: #2e91c7; color: white; display: flex; justify-content: space-between; ">
            <div class="link_click">
                <p>Linklere keçid</p>
                {{ userdata.clicklink }}
            </div> 

            <div class="link_click">
                <p>Coins</p>
                {{ userdata.coins }}
            </div> 
        </div>

    

        {% endfor %}

        {% for link in links %}

        
        <div style="padding: 10px; border:  1px black solid;">
            <h1>{{ link.name }}</h1>
            <a href="{{ link.get_absolute_url }}"><span class="baseurllink"></span>{{ link.get_absolute_url }}</a>

        </div>
          



        {% endfor %}

    
    </body>

    {% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% block base %}


    <body>
        <div class="container" style="margin-top: 20px;">
            <h3>Giris</h3>
            <form method="post">
            
                {% csrf_token %}
                {{ form|crispy }}
                
               <input type="submit" value="Qeydiyyatdan kec">
            </form>
        </div>
       </body> 
{% endblock %}